Repository ploomber/jupysql, pull requests merged in 2023-04, with the labels that each got.

#318 Drop sqlglot for generating CTEs
  src/sql/connection.py
  src/sql/magic.py
  src/sql/plot.py
  src/sql/run.py
  src/sql/store.py
  src/tests/test_command.py
  src/tests/test_compose.py
  src/tests/test_connection.py
  src/tests/test_store.py
Labels: Owner: Yafim

#370 fix `%sqlcmd tables/columns` in MySQL
  CHANGELOG.md
  doc/integrations/mariadb.ipynb
  doc/integrations/mysql.ipynb
  src/sql/inspect.py
  src/tests/test_inspect.py
Labels: Owner: Ido

#385 Improve connecting tutorial
  doc/connecting.md
Labels: Owner: Eduardo

#399 adds more methods for connecting to a db
  doc/connecting.md
  doc/integrations/mariadb.ipynb
  doc/integrations/mssql.ipynb
  doc/integrations/mysql.ipynb
  doc/quick-start.md
  doc/user-guide/FAQ.md
Labels: Owner: Ido

#341 %sqlcmd improvements
  CHANGELOG.md
  doc/_toc.yml
  doc/integrations/mindsdb.ipynb
  doc/integrations/mssql.ipynb
  doc/integrations/postgres-connect.ipynb
  doc/user-guide/tables-columns.md
  doc/user-guide/testing-columns.md
  src/sql/magic_cmd.py
  src/tests/integration/test_generic_db_operations.py
  src/tests/test_magic_cmd.py
Labels: Owner: Tony

#371 document how to generate vendor-agnostic SQL with sqlglot
  doc/community/developer-guide.md
Labels: Owner: Yafim

#431 migrating more error tracebacks
  CHANGELOG.md
  doc/community/developer-guide.md
  src/sql/connection.py
  src/sql/exceptions.py
  src/sql/inspect.py
  src/sql/magic.py
  src/sql/magic_cmd.py
  src/sql/magic_plot.py
  src/sql/run.py
  src/sql/store.py
  src/sql/util.py
  src/tests/integration/test_questDB.py
  src/tests/test_command.py
  src/tests/test_connection.py
  src/tests/test_inspect.py
  src/tests/test_magic.py
  src/tests/test_run.py
  src/tests/test_store.py
  src/tests/test_util.py
Labels: Owner: Ido
