Repository ploomber/jupysql, pull requests merged in 2023-03, with the labels that each got.

#274 230 customizing results output
  src/sql/run.py
  src/tests/conftest.py
  src/tests/test_magic.py
Labels: Owner: Eduardo

#259 postgres integration improvements
  doc/_toc.yml
  doc/api/configuration.md
  doc/conf.py
  doc/connecting.md
  doc/howto/postgres-install.md
  doc/integrations/postgres-connect.ipynb
Labels: Owner: Eduardo

#226 ggplot plotting API
  .gitignore
  doc/_toc.yml
  doc/user-guide/ggplot.md
  pyproject.toml
  src/sql/ggplot/__init__.py
  src/sql/ggplot/aes.py
  src/sql/ggplot/facet_wrap.py
  src/sql/ggplot/geom/__init__.py
  src/sql/ggplot/geom/geom.py
  src/sql/ggplot/geom/geom_boxplot.py
  src/sql/ggplot/geom/geom_histogram.py
  src/sql/ggplot/ggplot.py
  src/sql/plot.py
  src/tests/baseline_images/test_ggplot/boxplot.png
  src/tests/baseline_images/test_ggplot/facet_wrap_custom_fill.png
  src/tests/baseline_images/test_ggplot/facet_wrap_custom_fill_and_color.png
  src/tests/baseline_images/test_ggplot/facet_wrap_custom_stacked_histogram.png
  src/tests/baseline_images/test_ggplot/facet_wrap_custom_stacked_histogram_cmap.png
  src/tests/baseline_images/test_ggplot/facet_wrap_default.png
  src/tests/baseline_images/test_ggplot/facet_wrap_default_no_legend.png
  src/tests/baseline_images/test_ggplot/histogram_categorical.png
  src/tests/baseline_images/test_ggplot/histogram_categorical_combined.png
  src/tests/baseline_images/test_ggplot/histogram_custom_color.png
  src/tests/baseline_images/test_ggplot/histogram_custom_fill.png
  src/tests/baseline_images/test_ggplot/histogram_custom_fill_and_color.png
  src/tests/baseline_images/test_ggplot/histogram_default.png
  src/tests/baseline_images/test_ggplot/histogram_numeric_categorical_combined.png
  src/tests/baseline_images/test_ggplot/histogram_numeric_categorical_combined_custom_fill.png
  src/tests/baseline_images/test_ggplot/histogram_numeric_categorical_combined_custom_multi_color.png
  src/tests/baseline_images/test_ggplot/histogram_numeric_categorical_combined_custom_multi_fill.png
  src/tests/baseline_images/test_ggplot/histogram_stacked_custom_cmap.png
  src/tests/baseline_images/test_ggplot/histogram_stacked_custom_color.png
  src/tests/baseline_images/test_ggplot/histogram_stacked_custom_color_and_fill.png
  src/tests/baseline_images/test_ggplot/histogram_stacked_default.png
  src/tests/baseline_images/test_ggplot/histogram_stacked_large_bins.png
  src/tests/baseline_images/test_ggplot/histogram_with_default.png
  src/tests/test_ggplot.py
Labels: Owner: Eduardo

#293 interactive parametrized SQL queries
  CHANGELOG.md
  doc/_toc.yml
  doc/environment.yml
  doc/user-guide/interactive.md
  setup.py
  src/sql/magic.py
  src/tests/test_command.py
  src/tests/test_magic.py
  src/tests/test_parse.py
Labels: Owner: Eduardo

#240 documenting jupyter magics in docs
  doc/_toc.yml
  doc/quick-start.md
  doc/user-guide/FAQ.md
Labels: Owner: Tony

#300 CTE tutorial improvements
  CONTRIBUTING.md
  doc/compose.md
Labels: Owner: Eduardo

#320 Adds support for MSSQL
  .github/workflows/ci-integration-db.yaml
  doc/tutorials/etl.md
  setup.py
  src/sql/_testing.py
  src/sql/ggplot/__init__.py
  src/sql/ggplot/aes.py
  src/sql/ggplot/facet_wrap.py
  src/sql/ggplot/geom/__init__.py
  src/sql/ggplot/geom/geom_boxplot.py
  src/sql/ggplot/geom/geom_histogram.py
  src/sql/ggplot/ggplot.py
  src/sql/plot.py
  src/tests/integration/conftest.py
  src/tests/integration/test_containers.py
  src/tests/integration/test_generic_db_opeations.py
  src/tests/integration/test_mssql.py
  src/tests/test_ggplot.py
Labels: Owner: Tony

#323 SQL Autocompletion
  CHANGELOG.md
  doc/_toc.yml
  doc/howto/autocompletion.md
  doc/static/sql-autocompletion.png
Labels: Owner: Tony

#322 283 test feature
  doc/_toc.yml
  doc/howto/csv.md
Labels: Owner: Yafim

#325 Support for SqlMagic.polars_dataframe_kwargs
  CHANGELOG.md
  doc/api/configuration.md
  src/sql/magic.py
  src/sql/run.py
  src/tests/test_magic.py
  src/tests/test_run.py
Labels: Owner: Eduardo
