Repository ploomber/jupysql, pull requests merged in 2023-05, with the labels that each got.

#462 Change default displaylimit value
  CHANGELOG.md
  doc/api/configuration.md
  doc/community/vs.md
  src/sql/magic.py
  src/sql/run.py
  src/tests/test_magic.py
Labels: Owner: Ido

#400 SQLachemy error overriding
  CHANGELOG.md
  doc/community/developer-guide.md
  src/sql/__init__.py
  src/sql/connection.py
  src/sql/error_message.py
  src/sql/magic.py
  src/tests/conftest.py
  src/tests/integration/conftest.py
  src/tests/integration/test_postgreSQL.py
  src/tests/test_magic.py
  src/tests/test_syntax_errors.py
Labels: Owner: Tony

#493 Fix CI integration live issue
  .github/workflows/ci-integration-db-live.yaml
  setup.py
  src/sql/_testing.py
  src/tests/integration/conftest.py
  src/tests/integration/test_generic_db_operations.py
Labels: Owner: Yafim, allow-workflow-edits

#473 adds sql formatting guide
  doc/_toc.yml
  doc/howto/format-sql.ipynb
  doc/howto/syntax-highlighting.md
  doc/static/format-sql.gif
  doc/static/launch-on-binder.png
  environment.yml
Labels: Owner: Ido

#477 Oracle Integration testing
  doc/_toc.yml
  doc/community/developer-guide.md
  doc/conf.py
  doc/connecting.md
  doc/integrations/compatibility.md
  doc/integrations/oracle.ipynb
  setup.py
  src/sql/_testing.py
  src/tests/integration/conftest.py
  src/tests/integration/test_generic_db_operations.py
  src/tests/integration/test_oracle.py
Labels: allow-workflow-edits

#520 CD script not taking into account integration tests
  .github/workflows/ci-integration-db-live.yaml
  .github/workflows/ci-integration-db.yaml
  .github/workflows/ci.yaml
Labels: allow-workflow-edits

#527 adds `codespell`
  .github/workflows/ci.yaml
  doc/community/developer-guide.md
  doc/compose.md
  doc/howto.md
  doc/howto/json.md
  doc/integrations/duckdb.md
  doc/plot.md
  doc/tutorials/excel.md
  doc/user-guide/data-profiling.md
  doc/user-guide/interactive.md
  doc/user-guide/tables-columns.md
  pyproject.toml
  src/sql/_testing.py
  src/sql/command.py
  src/sql/magic_cmd.py
  src/sql/run.py
  src/tests/integration/conftest.py
  src/tests/integration/test_generic_db_operations.py
  src/tests/integration/test_questDB.py
  src/tests/test_magic.py
Labels: allow-workflow-edits

#440 --persist-replace argument
  CHANGELOG.md
  doc/integrations/pandas.md
  src/sql/magic.py
  src/tests/test_command.py
  src/tests/test_magic.py
  src/tests/test_parse.py
Labels: Owner: Yafim

#420 Table explorer
  CHANGELOG.md
  MANIFEST.in
  doc/_toc.yml
  doc/conf.py
  doc/user-guide/table_explorer.md
  setup.py
  src/sql/magic.py
  src/sql/magic_cmd.py
  src/sql/util.py
  src/sql/widgets/__init__.py
  src/sql/widgets/table_widget/__init__.py
  src/sql/widgets/table_widget/css/tableWidget.css
  src/sql/widgets/table_widget/js/tableWidget.js
  src/sql/widgets/table_widget/table_widget.py
  src/sql/widgets/utils.py
  src/tests/test_magic_cmd.py
  src/tests/test_util.py
  src/tests/test_widget.py
Labels: Owner: Tony

#535 Fix CI integration local issue
  .github/workflows/ci-integration-db.yaml
  src/tests/integration/test_generic_db_operations.py
  src/tests/integration/test_oracle.py
Labels: allow-workflow-edits
