Repository ploomber/jupysql, pull requests merged in 2024-01, with the labels that each got.

#977 Removing binder
  README.md
  doc/conf.py
  doc/howto/ggplot-interact.md
  doc/user-guide/table_explorer.ipynb
  environment.yml
  postBuild
  pyproject.toml
Labels: bug, no-changelog

#981 Document Snowflake Warehouse Fix
  doc/community/developer-guide.md
Labels: no-changelog

#982 Removed cloud tests workflow
  .github/workflows/ci-integration-db-sqlalchemy-v1.yaml
  .github/workflows/ci.yaml
  doc/community/developer-guide.md
  noxfile.py
  setup.py
  src/tests/integration/test_generic_db_operations.py
Labels: allow-workflow-edits, no-changelog

#976 Refactor close-matching when reading toml config
  src/sql/util.py
  src/tests/test_config.py
Labels: no-changelog

#988 Banner changed
  doc/conf.py
Labels: no-changelog
